      module filenames

      implicit none

      character(len=13),public  :: grdname_full='input/grdfile'
      character(len=13),public  :: frcname_full='input/frcfile'
      character(len=13),public  :: ininame_full='input/inifile'
      character(len=13),public  :: rivname_full='input/rivfile'
      character(len=13),public  :: bryname_full='input/bryfile'
      character(len=13),public  :: tidname_full='input/tidfile'

      end module filenames
